//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Page_Design.Organisations
{


    public partial class Shopee
    {

        /// <summary>
        /// im_organisation_profile_headerimage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image im_organisation_profile_headerimage;

        /// <summary>
        /// im_organisation_profilecard_logo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image im_organisation_profilecard_logo;

        /// <summary>
        /// lb_organisation_profilecard_name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_name;

        /// <summary>
        /// lb_organisation_profilecard_headline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_headline;

        /// <summary>
        /// lb_organisation_profilecard_website control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_website;

        /// <summary>
        /// lb_organisation_profilecard_employees control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_employees;

        /// <summary>
        /// lb_organisation_profilecard_employees_count control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_employees_count;

        /// <summary>
        /// lb_organisation_profilecard_headquarters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_headquarters;

        /// <summary>
        /// lb_organisation_profilecard_headquarters_location control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lb_organisation_profilecard_headquarters_location;

        /// <summary>
        /// lb_organisation_profile_reviewcontrols_searchbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox lb_organisation_profile_reviewcontrols_searchbar;

        /// <summary>
        /// bt_organisation_profile_reviewcontrols_searchbutton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button bt_organisation_profile_reviewcontrols_searchbutton;

        /// <summary>
        /// bt_organisation_profile_reviewcontrols_writereview control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button bt_organisation_profile_reviewcontrols_writereview;

        /// <summary>
        /// dd_organisation_profile_reviewcontrols_filter_jobstatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dd_organisation_profile_reviewcontrols_filter_jobstatus;

        /// <summary>
        /// dd_organisation_profile_reviewcontrols_filter_location control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dd_organisation_profile_reviewcontrols_filter_location;

        /// <summary>
        /// dd_organisation_profile_reviewcontrols_filter_rating control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dd_organisation_profile_reviewcontrols_filter_rating;

        /// <summary>
        /// dd_organisation_profile_reviewcontrols_sort control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dd_organisation_profile_reviewcontrols_sort;
    }
}
